### ISSUE TITLE
[HELP] How to solve the cluster single point problem？

### ISSUE THREAD

**Issue by AllenZMC** [openshift/microshift#1408] opened 2023-02-23 08:14 UTC
How to solve the cluster single point problem and improve high availability？

**Comment by dhellmann** [comment] 2023-02-23 16:30
I think you're asking what to do about the fact that microshift is currently only running in a single-node configuration. We made that choice because we have requirements to fit onto small standalone devices. There are other ways to run kubernetes on multiple nodes, including OpenShift, so if you have a hard requirement for multiple nodes one of those may be a better fit. If the requirement is for application availability, then running multiple instances of kubernetes with high availability tools at the application layer can also help.

Does that answer your question?

**Comment by AllenZMC** [comment] 2023-02-24 02:02
@dhellmann Thank you for your answer.

**Comment by ggiguash** [comment] 2023-02-24 05:57
@AllenZMC, MicroShift was designed for a quick restart. It should take up to 1m to start or restart the service assuming that the required container images are available on the device. 
If container images are not available, they will be downloaded as part of MicroShift bootstrap and it will take time depending on the network speed. 

Note that we have an option to embed container images in the device OS image. You can refer to the [Offline Containers](https://github.com/openshift/microshift/blob/main/docs/rhel4edge_iso.md#offline-containers) and subsequent sections in the documentation.

**Comment by AllenZMC** [comment] 2023-02-24 08:55
@ggiguash  Thanks.

**Comment by AllenZMC** [comment] 2023-02-27 02:24
@ggiguash @dhellmann  Does microshift use etcd?

**Comment by ggiguash** [comment] 2023-02-27 06:54
MicroShift uses `etcd` just like OpenShift. In 4.12 release, `etcd` functionality was embedded in the `microshift` process. Starting from 4.13, we are separating `etcd` into a separate service, which is managed by the `microshfit` process (see [ETCD-317](https://issues.redhat.com/browse/ETCD-317) epic).

For `harbor`, I'm not aware of us trying to integrate it with MicroShift. I think it "should" work, so I welcome you to try and report the results of that experiment.

**Comment by AllenZMC** [comment] 2023-02-28 13:03
@ggiguash  Thanks. 

What types of ocp api does mocroshift support?

**Comment by ggiguash** [comment] 2023-02-28 13:58
MicroShift supports minimal set of OCP APIs as described at the [Enabled OpenShift APIs](https://github.com/openshift/microshift/blob/main/docs/enabled_apis.md) page.

**Comment by AllenZMC** [comment] 2023-03-01 01:43
@ggiguash Do these api groups support, see https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.12/html/api_reference/understanding-api-support-tiers#mapping-support-tiers-to-openshift-api-groups_understanding-api-tiers?

**Comment by dhellmann** [comment] 2023-03-01 14:50
> @ggiguash Do these api groups support ? See https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.12/html/api_reference/understanding-api-support-tiers#mapping-support-tiers-to-openshift-api-groups_understanding-api-tiers

That page lists the support tiers for groups of APIs to explain how they are supported generally by Red Hat, but most of those APIs are not actually in MicroShift.

**Comment by AllenZMC** [comment] 2023-03-02 11:26
@dhellmann Thanks. BTW, What are the currently determined ocp apis, except for route and scc

**Comment by AllenZMC** [comment] 2023-03-02 11:49
@ggiguash Got it, are there any documentation tutorials for installing on a virtual machine?

**Comment by ggiguash** [comment] 2023-03-07 07:20
@AllenZMC , please review the docs at https://github.com/openshift/microshift/tree/main/docs. This folder contains all the information you need.

I'm closing this issue for now as we finished discussing the main topic. Feel free to open other issues if there are further questions.

/close

**Closed** 2023-03-07 07:21 UTC
