### ISSUE TITLE
[Enhancement]: Add CLI commands to configure storage, VG, PVs, in MicroShift docs

### ISSUE THREAD

**Issue by wabouhamad** [openshift/microshift#1564] opened 2023-03-24 14:58 UTC
#### Design document link
https://access.redhat.com/documentation/en-us/red_hat_build_of_microshift/4.12/html/installing/microshift-install-rpm?extIdCarryOver=true&sc_cid=701f2000001Css5AAC

In section 1.2, for Storage Configuration, you only have the graphical RHEL installer steps.
PR: #<PR number>

#### What would you like to be added?
Steps and command to create VG and PVs from CLI, and how to make them persist after a reboot
#### Why is this needed?
These steps can be executed from an ssh session to the instance running Microshift.  UI interface may not be accessible to everyone

**Comment by dhellmann** [comment] 2023-03-24 21:06
Hi, @wabouhamad , thanks for this issue! Could you file feedback on the documentation directly, please, by selecting some relevant text and use the feedback UI that appears on the page. That will ensure the issue is routed to the documentation team, since they are not watching for issues here on the code repository.

**Comment by wabouhamad** [comment] 2023-04-04 16:42
Just added that comment in the Feedback section.  Thank you.

**Comment by dhellmann** [comment] 2023-04-04 16:50
Thanks! I'm going to close this ticket, and we'll track the doc update in Jira.

**Closed by dhellmann** 2023-04-04 16:50 UTC
